type Todo @expose(introspectable: true) {
  id: ID!
  text: String!
  done: Boolean!
  user: User!
  isGlobal: Boolean @hide
}

type User @expose(introspectable: true) {
  id: ID!
  name: String!
}

input NewTodo @expose(introspectable: true) {
  text: String!
  userId: String!
  isGlobal: Boolean @hide
}

type Query {
  todos: [Todo!]! @expose(introspectable: true)
  internalQuery: Boolean!
}

type Mutation {
  createTodo(input: NewTodo!): Todo! @expose(introspectable: true)
  internalMutation: Boolean!
}
