name: Release

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Tag for the new release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_notes:
        description: 'Release notes or changelog for this release'
        required: true
        default: 'Add release notes here'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Publish Go Module
        run: |
          go mod tidy
          go mod verify

      - name: Create Git Tag
        run: |
          git tag ${{ inputs.version_tag }}
          git push origin ${{ inputs.version_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version_tag }}
          name: Release ${{ inputs.version_tag }}
          body: ${{ inputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
